# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    exclude:
    - azure-pipelines-release.yml
    - readme.md

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  releaseSuffix: ''

name: 3.2.$(date:yyMM).$(date:dd)$(rev:r)
steps:  
- task: NuGetToolInstaller@1
  displayName: Install Latest Nuget

- task: DotNetCoreCLI@2
  displayName: Restore Packages
  inputs:
    command: 'restore'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: dotnet build
  inputs:
    projects: '$(solution)'
    arguments: '--configuration=$(buildConfiguration) /p:Platform="$(buildPlatform)" /p:Version=$(Build.BuildNumber) /p:AssemblyVersion=$(Build.BuildNumber) /p:FileVersion=$(Build.BuildNumber) '
    
- task: CopyFiles@2
  displayName: Copy Files to $(build.artifactstagingdirectory)
  inputs:
    SourceFolder: '$(system.defaultworkingdirectory)'
    Contents: '**/Dsoft.*.nupkg'
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts drop
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
